export const universityUrls: Record<string, string> = {
  "Sage University": "https://www.sageuniversity.edu.in",
  "Vaishnav University": "https://www.vaishnav.ac.in",
  "Renaissance University": "https://www.ruh.ac.in",
  "LNCT University": "https://www.lnct.ac.in",
  "Chameli Devi Institute": "https://www.cdgi.edu.in",
  "Chameli Devi Institute of Management": "https://www.cdgi.edu.in",
  "Malwa Institute": "https://www.mitm.ac.in",
  "Malwa Institute of Technology & Management": "https://www.mitm.ac.in",
  "IPS Academy": "https://www.ipsacademy.org",
  "Medicaps University": "https://www.medicaps.ac.in",
  "Prestige University": "https://www.prestigeuniversity.ac.in",
  "Jaipuria Institute": "https://www.jaipuria.ac.in",
  "Amity Business School": "https://www.amity.edu/indore",
  "Oriental College": "https://www.orientalcollegeindore.com",
  "Graduate Business School": "https://www.gbs.ac.in",
  "Softvision College": "https://www.softvision.ac.in",
  "Aurobindo College": "https://www.aurobindocollege.ac.in",
  "Astral College": "https://www.astralcollege.ac.in",
  "Oxford College": "https://www.oxfordindore.com",
  "Arihant College": "https://www.arihantcollege.ac.in",
  "Altius College": "https://www.altiuscollege.in",
  "ISBA College": "https://www.isba.ac.in",
  "IMI College": "https://www.imibhopal.ac.in",
  "Jain Dewakar College": "https://www.jaindewakar.ac.in",
  "Patel College": "https://www.patelcollege.ac.in",
  "BM College": "https://www.bmcollege.ac.in",
  "RD Memorial College": "https://www.rdmemorial.ac.in",
  "Kewalshree College": "https://www.kewalshree.ac.in",
  "Modern College": "https://www.moderncollege.ac.in",
  "Vishishth School of Management": "https://www.vsm.ac.in",
  "New Era College Mhow": "https://www.neweracollege.ac.in",
  "Vikrant College": "https://www.vikrantcollege.ac.in",
  "Parijat College": "https://www.parijatcollege.ac.in",
  "Gurukul College": "https://www.gurukulcollege.ac.in",
  "Indore Institute of Law": "https://www.indorelawcollege.com",
  "Radiant Institute": "https://www.radiantinstitute.ac.in",
  "Radiant Institute of Management": "https://www.radiantinstitute.ac.in",
  "Avantika University Ujjain": "https://www.avantikauniversity.edu.in",
  "Avantika University": "https://www.avantikauniversity.edu.in",
  "PIEMR Indore": "https://www.piemr.edu.in",
  "Renaissance College DAVV": "https://www.ruc.ac.in",
  "Alliance University Bangalore": "https://www.alliance.edu.in",
  "Alliance University": "https://www.alliance.edu.in",
  "RV University Bangalore": "https://www.rvu.edu.in",
  "RV University": "https://www.rvu.edu.in",
  "GD Goenka University Gurugram": "https://www.gdgoenkauniversity.com",
  "GD Goenka University": "https://www.gdgoenkauniversity.com",
  "SGT University Gurugram": "https://www.sgtuniversity.ac.in",
  "SGT University": "https://www.sgtuniversity.ac.in",
  "IILM Greater Noida": "https://www.iilm.edu",
  "IILM University Greater Noida": "https://www.iilm.edu",
  "Graphic Era University Dehradun": "https://www.graphicera.edu.in",
  "Graphic Era University": "https://www.graphicera.edu.in",
  "Ganpat University Gujarat": "https://www.ganpatuniversity.ac.in",
  "Ganpat University": "https://www.ganpatuniversity.ac.in",
  "Karnavati University Gujarat": "https://www.karnavatiuniversity.edu.in",
  "Karnavati University": "https://www.karnavatiuniversity.edu.in",
  "SPSU Udaipur": "https://www.spsu.ac.in",
  "NIMS Jaipur": "https://www.nimsuniversity.org",
  "NIMS University Jaipur": "https://www.nimsuniversity.org",
  "NIMS University": "https://www.nimsuniversity.org",
  "Bennett University": "https://www.bennett.edu.in",
  "ISMS Pune": "https://www.ismsgroup.ac.in",
}
